// Generated by scripts/build-web-logos.py. Do not edit by hand.
export const logoSizes = {
  "rm-and-co": { width: 720, height: 196 },
  "rm-digital": { width: 720, height: 174 },
  "rm-digital-reversed": { width: 720, height: 187 },
  "rm-mobility": { width: 720, height: 167 },
  "rm-capital": { width: 720, height: 173 },
  "rm-industrial": { width: 720, height: 181 },
  "fleetorbit": { width: 720, height: 173 },
  "shopping-lyst": { width: 720, height: 178 },
  "openwheels": { width: 563, height: 420 },
  "field-force": { width: 640, height: 177 },
  "rm-risk": { width: 720, height: 212 },
  "element-bridge": { width: 720, height: 235 },
} as const;

export type LogoId = keyof typeof logoSizes;
