import test from 'node:test';
import assert from 'node:assert/strict';
import {create,step,metrics,occupancy,defaults,compare,disposition,inject,otif} from '../public/businesses/rm-industrial/egoli/twin-sim.mjs';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
test('liquid, kits and order demand reconcile under disruptions across multiple seeds',()=>{
 for(const seed of [1,7,42,83]){const s=create(seed);for(let i=0;i<96*21;i++){if(i===200)inject(s,'kits');if(i===300)inject(s,'rush');if(i===400)inject(s,'labels');step(s);const m=metrics(s);close(m.balance,0);close(m.kitBalance,0);close(s.totals.demand,m.backlog+s.totals.shipped+s.lost);for(const v of [s.kits,s.released,s.cur,s.filled,s.fg])assert(v>=-1e-7);assert(occupancy(s)<=s.cfg.tankCap+1e-7);assert(s.filled<=s.cfg.filledCap+1e-7);assert(s.fg<=s.cfg.fgCap+1e-7);}}
});
test('held lots never auto-release; only eligible explicit disposition moves stock',()=>{const s=create(7,{qaHoldProb:1});for(let i=0;i<96*3;i++)step(s);const lot=s.lots.find(l=>l.state==='hold'&&s.t>=l.holdUntil);assert(lot);const id=lot.id,qty=lot.qty,before=s.released;disposition(s,id,'release');close(s.released,before+qty);close(metrics(s).balance,0);const remaining=s.lots.find(l=>l.state==='hold'&&s.t>=l.holdUntil);assert(remaining);disposition(s,remaining.id,'reject');close(metrics(s).balance,0);assert(s.decisions.length===2)});
test('hold review cannot be bypassed',()=>{const s=create(7,{qaHoldProb:1});for(let i=0;i<33;i++)step(s);const lot=s.lots.find(l=>l.state==='hold');assert(lot);assert.throws(()=>disposition(s,lot.id,'release'),/investigation/)});
test('dispatch consumes whole units and QA is weekday/window gated',()=>{const s=create(7,{upstreamBreakProb:0,stopProb:0,qaHoldProb:0});for(let i=0;i<32;i++)step(s);close(s.released,0);step(s);assert(s.released>0);for(let i=0;i<96*8;i++)step(s);assert(s.shipments.every(x=>Number.isInteger(x.qty)));assert(s.shipments.every(x=>[9,14].includes(x.t%24)&&Math.floor(x.t/24)%7<5));});
test('paired runs are deterministic with equal demand events and no live-run mutation',()=>{const a=compare(7,defaults,{...defaults,bottlingRate:320}),b=compare(7,defaults,{...defaults,bottlingRate:320});assert.deepEqual(a,b);close(a.baseline.demand7,a.scenario.demand7);const same=compare(7,defaults,defaults);assert.deepEqual(same.baseline,same.scenario)});
test('OTIF uses due-order cohort including open late and cancelled orders',()=>{const s=create();s.t=100;s.done=[{due:90,doneAt:89},{due:91,doneAt:95}];s.orders=[{due:92,doneAt:null}];s.expired=[{due:93,doneAt:null}];close(otif(s),.25);});
test('invalid parameters and arbitrary step sizes rejected',()=>{assert.throws(()=>create(1,{lotSize:9000,tankCap:8000}));assert.throws(()=>create(1,{dwell:0}));assert.throws(()=>create(1,{qaWindows:[8,8]}));assert.throws(()=>step(create(),1));});
