import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "RM Digital", description: "RM Digital builds enterprise software and data products. Field Force is its sales-performance and insurance-distribution workflow product." };

export default function RmDigital() {
  return <><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">RM</span><span><strong>RM &amp; CO.</strong><small>Holdings &amp; operating company</small></span></Link><nav><Link href="/">Group</Link><Link href="#capabilities">Capabilities</Link><a className="nav-cta" href="https://fieldforce.rmandco.co.za">Field Force</a></nav></header><main>
    <section className="hero digital-hero"><div className="hero-copy"><p className="eyebrow">RM &amp; Co. / Business 02</p><h1>RM Digital</h1><p>We build software around the work that matters: structured workflows, operational visibility, trustworthy reporting and practical intelligence.</p><div className="actions"><a className="button primary" href="https://fieldforce.rmandco.co.za">Explore Field Force</a><Link className="button ghost" href="/">Back to the group</Link></div></div><aside className="hero-aside"><span>Product portfolio</span><strong>Field Force</strong><p>A sales-performance and insurance-distribution workflow platform for field teams, operations and compliance.</p><a href="https://fieldforce.rmandco.co.za">Visit product site <b>↗</b></a></aside></section>
    <section className="section manifesto" id="capabilities"><p className="section-no">01 / What we build</p><div><h2>Digital products grounded in real operations.</h2><div className="prose"><p>RM Digital translates field processes, source documents and fragmented reporting into clear systems that help teams execute, supervise and improve.</p><p>Our products are designed to preserve source truth, expose data gaps and scale from operational pilots into durable enterprise platforms.</p></div></div></section>
    <section className="section businesses"><div className="section-heading"><div><p className="section-no">02 / Flagship product</p><h2>Field Force</h2></div><p>One operating view for field sales performance, source-controlled evidence, commission reconciliation and the workflows that connect them.</p></div><div className="business-grid"><article className="business-card featured"><span>01</span><small>Performance</small><h3>Sales intelligence</h3><p>Targets, trends, team comparisons and adviser-level coaching signals.</p></article><article className="business-card"><span>02</span><small>Operations</small><h3>Workflow control</h3><p>Structured intake, evidence requirements and source-aware queues.</p></article><article className="business-card"><span>03</span><small>Trust</small><h3>Honest reporting</h3><p>Unavailable measures remain unavailable until their real source is connected.</p></article></div></section>
    <section className="section contact"><div><p className="section-no">03 / Work with RM Digital</p><h2>Turn operational complexity into a product advantage.</h2></div><div><p>Talk to us about a Field Force pilot, a workflow product or a strategic digital partnership.</p><a className="button primary" href="mailto:hello@rmandco.co.za">Start a conversation</a></div></section>
  </main><footer><Link className="brand" href="/"><span className="brand-mark">RM</span><span><strong>RM DIGITAL</strong><small>A subsidiary of RM &amp; Co.</small></span></Link><p>Field Force is a product of RM Digital.</p><span>© 2026 RM &amp; Co.</span></footer></>;
}
