#!/usr/bin/env python3
"""Build web-display derivatives of the approved logos.

The approved files in public/brand keep large transparent margins that differ from logo to logo
(RM Digital's lockup fills 45% of its canvas, FleetOrbit's 96%), so a shared CSS box renders them
at very different visible sizes. This script trims each logo to its artwork and resizes it for the
screen. The artwork itself is not redrawn, recoloured or altered; originals are never modified.

Writes public/brand/web/*.png and app/components/logo-data.ts (intrinsic sizes for the Logo component).
Run from the site root:  python3 scripts/build-web-logos.py   (needs Pillow)
"""
import base64
import re
from pathlib import Path

from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / "public" / "brand"
OUT = BRAND / "web"
MAX_W, MAX_H = 720, 420  # 2x the largest size any logo is displayed at

# slug -> (source file, optional crop box in source pixels)
SOURCES = {
    "rm-and-co": "rm-and-co/horizontal-lockup.png",
    "rm-digital": "rm-digital/horizontal-lockup.png",
    "rm-digital-reversed": "rm-digital/reversed-lockup.png",
    "rm-mobility": "rm-mobility/horizontal-lockup.png",
    "rm-capital": "rm-capital/horizontal-lockup.png",
    "rm-industrial": "rm-industrial/horizontal-lockup.png",
    "fleetorbit": "products/fleetorbit.png",
    "shopping-lyst": "products/ShoppingLyst.png",
    "openwheels": "products/openwheels.png",
    "field-force": "products/field-force.png",
}
# The RM Risk horizontal lockup is shown from the supplied logo sheet. This is the exact region the
# site previously framed with a CSS viewport (1368x440 at 40,160 of the 1448x1086 sheet).
RISK_SHEET = ("rm-risk/approved-logo-sheet.png", (40, 160, 1408, 600))
# The Element Bridge SVG only wraps a raster image; use that raster directly.
ELEMENT_BRIDGE_SVG = "element-bridge/horizontal-lockup.svg"


def content_box(im: Image.Image):
    alpha = im.getchannel("A").point(lambda v: 255 if v > 8 else 0)
    box = alpha.getbbox()
    if box and box != (0, 0, *im.size):
        return box
    # Opaque image: trim the flat background colour instead.
    rgb = im.convert("RGB")
    bg = Image.new("RGB", rgb.size, rgb.getpixel((0, 0)))
    return ImageChops.difference(rgb, bg).convert("L").point(lambda v: 255 if v > 24 else 0).getbbox()


def finish(im: Image.Image, slug: str, pad_ratio=0.02):
    im = im.convert("RGBA")
    l, t, r, b = content_box(im)
    pad = round((b - t) * pad_ratio)
    im = im.crop((max(l - pad, 0), max(t - pad, 0), min(r + pad, im.width), min(b + pad, im.height)))
    scale = min(MAX_W / im.width, MAX_H / im.height, 1)
    if scale < 1:
        im = im.resize((round(im.width * scale), round(im.height * scale)), Image.LANCZOS)
    path = OUT / f"{slug}.png"
    im.save(path, optimize=True)
    print(f"{slug:22s} {im.width:4d}x{im.height:<4d} {path.stat().st_size / 1024:6.1f} KB")
    return im.size


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    sizes = {}
    for slug, rel in SOURCES.items():
        sizes[slug] = finish(Image.open(BRAND / rel), slug)

    sheet, box = RISK_SHEET
    sizes["rm-risk"] = finish(Image.open(BRAND / sheet).crop(box), "rm-risk")

    svg = (BRAND / ELEMENT_BRIDGE_SVG).read_text()
    data = re.search(r'href="data:image/png;base64,([^"]+)"', svg).group(1)
    tmp = OUT / "_element-bridge-src.png"
    tmp.write_bytes(base64.b64decode(data))
    sizes["element-bridge"] = finish(Image.open(tmp), "element-bridge")
    tmp.unlink()

    rows = "\n".join(f'  "{s}": {{ width: {w}, height: {h} }},' for s, (w, h) in sizes.items())
    (ROOT / "app" / "components" / "logo-data.ts").write_text(
        "// Generated by scripts/build-web-logos.py. Do not edit by hand.\n"
        "export const logoSizes = {\n" + rows + "\n} as const;\n\n"
        "export type LogoId = keyof typeof logoSizes;\n"
    )


if __name__ == "__main__":
    main()
